import type { CostCategory, Difficulty } from "@/lib/types";

export interface RecipeSeed {
  title: string;
  description: string;
  steps: string[];
  timeMinutes: number;
  difficulty: Difficulty;
  equipment: string[];
  estimatedCost: CostCategory;
  tags: string[];
  graphPath: string[];
  ingredients: Array<{ slug: string; quantity?: string; optional?: boolean }>;
  componentSlugs: string[];
}

export const RECIPES: RecipeSeed[] = [
  // Barely any ingredients
  {
    title: "Butter on Toast",
    description: "The classic emergency meal.",
    steps: [
      "Toast the bread.",
      "Spread butter while hot.",
      "Eat immediately.",
    ],
    timeMinutes: 3,
    difficulty: "easy",
    equipment: ["toaster"],
    estimatedCost: "very_cheap",
    tags: ["toast", "barely-any", "breakfast"],
    graphPath: ["toast-bread", "butter-toast"],
    ingredients: [
      { slug: "bread" },
      { slug: "butter" },
    ],
    componentSlugs: ["toast", "buttered-toast"],
  },
  {
    title: "Fried Egg on Toast",
    description: "One pan, one toaster, proper food.",
    steps: [
      "Toast the bread.",
      "Fry the egg in butter until the white sets.",
      "Slide onto toast and season.",
    ],
    timeMinutes: 7,
    difficulty: "easy",
    equipment: ["pan", "hob", "toaster"],
    estimatedCost: "very_cheap",
    tags: ["egg", "toast", "barely-any"],
    graphPath: ["toast-bread", "fry-egg-butter"],
    ingredients: [
      { slug: "bread" },
      { slug: "eggs" },
      { slug: "butter" },
      { slug: "salt", optional: true },
      { slug: "pepper", optional: true },
    ],
    componentSlugs: ["toast", "fried-egg"],
  },
  {
    title: "Microwave Scrambled Eggs",
    description: "Eggs when you can't be bothered with a pan.",
    steps: [
      "Beat eggs in a microwave-safe bowl with a splash of milk if you have it.",
      "Microwave 30 seconds, stir, repeat until just set.",
      "Season and eat.",
    ],
    timeMinutes: 4,
    difficulty: "easy",
    equipment: ["microwave", "bowl"],
    estimatedCost: "very_cheap",
    tags: ["egg", "microwave", "barely-any"],
    graphPath: ["microwave-egg"],
    ingredients: [
      { slug: "eggs" },
      { slug: "milk", optional: true },
      { slug: "butter", optional: true },
      { slug: "salt", optional: true },
    ],
    componentSlugs: ["microwave-scrambled-egg"],
  },
  {
    title: "Beans on Toast",
    description: "Student legend. No notes.",
    steps: [
      "Toast the bread.",
      "Microwave the beans until hot.",
      "Pour over toast. Add cheese if you have it.",
    ],
    timeMinutes: 5,
    difficulty: "easy",
    equipment: ["toaster", "microwave", "bowl"],
    estimatedCost: "very_cheap",
    tags: ["beans", "toast", "barely-any"],
    graphPath: ["toast-bread", "heat-beans"],
    ingredients: [
      { slug: "bread" },
      { slug: "baked-beans" },
      { slug: "cheese", optional: true },
      { slug: "butter", optional: true },
    ],
    componentSlugs: ["toast", "hot-beans"],
  },
  {
    title: "Cheesy Beans on Toast",
    description: "Beans on toast, but you actually feel looked after.",
    steps: [
      "Toast the bread and butter it.",
      "Heat the beans.",
      "Pile beans on toast and cover with cheese.",
      "Grill or microwave until the cheese melts.",
    ],
    timeMinutes: 7,
    difficulty: "easy",
    equipment: ["toaster", "microwave", "grill"],
    estimatedCost: "cheap",
    tags: ["beans", "toast", "cheese"],
    graphPath: ["toast-bread", "heat-beans", "cheesy-beans-on-toast"],
    ingredients: [
      { slug: "bread" },
      { slug: "baked-beans" },
      { slug: "cheese" },
      { slug: "butter", optional: true },
    ],
    componentSlugs: ["toast", "hot-beans", "cheesy-beans-toast"],
  },

  // Egg meals
  {
    title: "Cheese Omelette",
    description: "Folded eggs, melted cheese, done.",
    steps: [
      "Beat eggs with a little milk if you have it.",
      "Melt butter in a pan and pour in the eggs.",
      "When nearly set, add cheese and fold.",
      "Slide onto a plate.",
    ],
    timeMinutes: 8,
    difficulty: "easy",
    equipment: ["pan", "hob"],
    estimatedCost: "cheap",
    tags: ["egg", "cheese", "vegetarian"],
    graphPath: ["omelette-base"],
    ingredients: [
      { slug: "eggs" },
      { slug: "butter" },
      { slug: "cheese" },
      { slug: "milk", optional: true },
    ],
    componentSlugs: ["omelette"],
  },
  {
    title: "Onion Omelette",
    description: "Soft onions inside a quick omelette.",
    steps: [
      "Fry chopped onion in butter until soft.",
      "Beat eggs and pour over the onions.",
      "Cook until set, fold, and eat.",
    ],
    timeMinutes: 10,
    difficulty: "easy",
    equipment: ["pan", "hob"],
    estimatedCost: "very_cheap",
    tags: ["egg", "onion", "vegetarian"],
    graphPath: ["fry-onion-butter", "omelette-base"],
    ingredients: [
      { slug: "eggs" },
      { slug: "onions" },
      { slug: "butter" },
      { slug: "cheese", optional: true },
    ],
    componentSlugs: ["fried-onion", "omelette"],
  },
  {
    title: "Cheesy Egg Toast",
    description: "Toast, fried egg, cheese. Hunger solved.",
    steps: [
      "Toast the bread.",
      "Fry an egg in butter.",
      "Put egg on toast, cover with cheese, melt briefly if you want.",
    ],
    timeMinutes: 8,
    difficulty: "easy",
    equipment: ["pan", "hob", "toaster"],
    estimatedCost: "cheap",
    tags: ["egg", "toast", "cheese"],
    graphPath: ["toast-bread", "fry-egg-butter", "cheesy-egg-toast-assembly"],
    ingredients: [
      { slug: "bread" },
      { slug: "eggs" },
      { slug: "cheese" },
      { slug: "butter" },
    ],
    componentSlugs: ["toast", "fried-egg", "cheesy-egg-toast"],
  },

  // Rice meals
  {
    title: "Mushroom Egg Fried Rice",
    description: "The classic student fried rice from random fridge bits.",
    steps: [
      "Fry the onion and mushrooms in butter.",
      "Push them aside and scramble the eggs.",
      "Add the rice (microwave pouch or leftover).",
      "Fry until the rice gets some colour.",
      "Stir through cheese if using.",
      "Season and eat.",
    ],
    timeMinutes: 12,
    difficulty: "easy",
    equipment: ["pan", "hob"],
    estimatedCost: "cheap",
    tags: ["rice", "egg", "mushroom", "one-pan"],
    graphPath: ["cook-microwave-rice", "fry-mushroom-onion", "mushroom-egg-fried-rice"],
    ingredients: [
      { slug: "microwave-rice", optional: true },
      { slug: "rice", optional: true },
      { slug: "eggs" },
      { slug: "mushrooms" },
      { slug: "onions" },
      { slug: "butter" },
      { slug: "cheese", optional: true },
      { slug: "soy-sauce", optional: true },
    ],
    componentSlugs: ["cooked-rice", "fried-mushroom-onion", "mushroom-egg-fried-rice"],
  },
  {
    title: "Crispy Cheesy Mushroom Rice",
    description: "Same base idea, but leave the rice to catch on the pan.",
    steps: [
      "Fry mushrooms and onion in butter.",
      "Add cooked rice and press it down.",
      "Leave it alone for a couple of minutes so the bottom crisps.",
      "Stir through eggs and cheese.",
      "Season with soy if you have it.",
    ],
    timeMinutes: 14,
    difficulty: "easy",
    equipment: ["pan", "hob"],
    estimatedCost: "cheap",
    tags: ["rice", "egg", "mushroom", "cheese", "one-pan"],
    graphPath: ["boil-rice", "fry-mushroom-onion", "mushroom-egg-fried-rice"],
    ingredients: [
      { slug: "rice" },
      { slug: "eggs" },
      { slug: "mushrooms" },
      { slug: "onions" },
      { slug: "butter" },
      { slug: "cheese" },
      { slug: "soy-sauce", optional: true },
    ],
    componentSlugs: ["cooked-rice", "fried-mushroom-onion", "mushroom-egg-fried-rice"],
  },
  {
    title: "Mushroom Rice with Fried Eggs",
    description: "Rice bowl topped with a proper fried egg.",
    steps: [
      "Fry mushrooms and onion.",
      "Stir through cooked rice.",
      "In the same pan or a second side, fry eggs.",
      "Serve rice topped with eggs and cheese.",
    ],
    timeMinutes: 13,
    difficulty: "easy",
    equipment: ["pan", "hob"],
    estimatedCost: "cheap",
    tags: ["rice", "egg", "mushroom"],
    graphPath: ["cook-microwave-rice", "fry-mushroom-onion", "fry-egg-butter"],
    ingredients: [
      { slug: "microwave-rice" },
      { slug: "eggs" },
      { slug: "mushrooms" },
      { slug: "onions" },
      { slug: "butter" },
      { slug: "cheese", optional: true },
    ],
    componentSlugs: ["cooked-rice", "fried-mushroom-onion", "fried-egg"],
  },
  {
    title: "Cheesy Mushroom Rice Bowl",
    description: "No egg version — still solid.",
    steps: [
      "Fry mushrooms and onion in butter.",
      "Add rice and heat through.",
      "Stir through lots of cheese.",
      "Season and eat from the pan if you want.",
    ],
    timeMinutes: 10,
    difficulty: "easy",
    equipment: ["pan", "hob"],
    estimatedCost: "cheap",
    tags: ["rice", "mushroom", "cheese", "vegetarian"],
    graphPath: ["cook-microwave-rice", "fry-mushroom-onion"],
    ingredients: [
      { slug: "microwave-rice" },
      { slug: "mushrooms" },
      { slug: "onions" },
      { slug: "butter" },
      { slug: "cheese" },
    ],
    componentSlugs: ["cooked-rice", "fried-mushroom-onion"],
  },
  {
    title: "Egg Fried Rice",
    description: "Eggs, rice, soy. The holy trinity.",
    steps: [
      "Heat oil or butter in a pan.",
      "Scramble the eggs.",
      "Add cooked rice and break it up.",
      "Add soy sauce and fry until hot.",
    ],
    timeMinutes: 10,
    difficulty: "easy",
    equipment: ["pan", "hob"],
    estimatedCost: "very_cheap",
    tags: ["rice", "egg", "one-pan"],
    graphPath: ["cook-microwave-rice", "egg-rice"],
    ingredients: [
      { slug: "microwave-rice", optional: true },
      { slug: "rice", optional: true },
      { slug: "eggs" },
      { slug: "oil", optional: true },
      { slug: "butter", optional: true },
      { slug: "soy-sauce", optional: true },
      { slug: "frozen-peas", optional: true },
    ],
    componentSlugs: ["cooked-rice", "egg-rice"],
  },
  {
    title: "Quick Vegetable Curry Rice",
    description: "Ready curry, frozen veg, rice. Microwave-friendly.",
    steps: [
      "Heat the microwave rice.",
      "Microwave the curry and frozen veg until hot.",
      "Serve curry over rice.",
    ],
    timeMinutes: 8,
    difficulty: "easy",
    equipment: ["microwave", "bowl"],
    estimatedCost: "moderate",
    tags: ["rice", "curry", "microwave", "vegetarian"],
    graphPath: ["cook-microwave-rice", "curry-sauce-quick", "veg-curry-rice"],
    ingredients: [
      { slug: "microwave-rice" },
      { slug: "ready-made-curry" },
      { slug: "frozen-mixed-vegetables", optional: true },
    ],
    componentSlugs: ["cooked-rice", "quick-curry", "veg-curry-rice"],
  },
  {
    title: "Chickpea Tomato Rice",
    description: "Cheap cupboard curry-ish bowl without a jar.",
    steps: [
      "Fry onion in oil.",
      "Add chickpeas, chopped tomatoes, and curry powder.",
      "Simmer 8 minutes.",
      "Serve over rice.",
    ],
    timeMinutes: 15,
    difficulty: "easy",
    equipment: ["pan", "hob"],
    estimatedCost: "very_cheap",
    tags: ["rice", "chickpeas", "vegetarian", "cupboard"],
    graphPath: ["boil-rice", "chickpea-curry-base"],
    ingredients: [
      { slug: "rice" },
      { slug: "chickpeas" },
      { slug: "chopped-tomatoes" },
      { slug: "onions" },
      { slug: "curry-powder" },
      { slug: "oil" },
      { slug: "garlic", optional: true },
    ],
    componentSlugs: ["cooked-rice", "chickpea-curry"],
  },

  // Pasta meals
  {
    title: "Cheesy Tomato Pasta",
    description: "Pasta, sauce, cheese. Minimal drama.",
    steps: [
      "Boil the pasta.",
      "Heat the pasta sauce or chopped tomatoes with garlic if you have it.",
      "Drain pasta, mix with sauce, bury in cheese.",
    ],
    timeMinutes: 15,
    difficulty: "easy",
    equipment: ["pan", "hob"],
    estimatedCost: "cheap",
    tags: ["pasta", "cheese", "vegetarian"],
    graphPath: ["boil-pasta", "quick-pasta-sauce", "pasta-tomato-cheese"],
    ingredients: [
      { slug: "pasta" },
      { slug: "tomato-pasta-sauce", optional: true },
      { slug: "chopped-tomatoes", optional: true },
      { slug: "cheese" },
      { slug: "garlic", optional: true },
      { slug: "oil", optional: true },
    ],
    componentSlugs: ["cooked-pasta", "ready-pasta-sauce", "cheesy-tomato-pasta"],
  },
  {
    title: "One-Pan Tomato Onion Pasta",
    description: "Proper sauce from tinned tomatoes and onion.",
    steps: [
      "Fry onion and garlic in oil.",
      "Add chopped tomatoes and a crumbled stock cube.",
      "Simmer while pasta cooks.",
      "Combine and add cheese.",
    ],
    timeMinutes: 18,
    difficulty: "easy",
    equipment: ["pan", "hob"],
    estimatedCost: "very_cheap",
    tags: ["pasta", "vegetarian", "cupboard"],
    graphPath: ["boil-pasta", "basic-tomato-sauce"],
    ingredients: [
      { slug: "pasta" },
      { slug: "chopped-tomatoes" },
      { slug: "onions" },
      { slug: "garlic" },
      { slug: "oil" },
      { slug: "stock-cubes", optional: true },
      { slug: "cheese", optional: true },
    ],
    componentSlugs: ["cooked-pasta", "basic-tomato-sauce"],
  },
  {
    title: "Tuna Pasta",
    description: "Cupboard pasta that actually fills you up.",
    steps: [
      "Boil pasta.",
      "Warm chopped tomatoes or pasta sauce with tuna stirred through.",
      "Mix with pasta and cheese if available.",
    ],
    timeMinutes: 15,
    difficulty: "easy",
    equipment: ["pan", "hob"],
    estimatedCost: "cheap",
    tags: ["pasta", "tuna", "cupboard"],
    graphPath: ["boil-pasta"],
    ingredients: [
      { slug: "pasta" },
      { slug: "tuna" },
      { slug: "chopped-tomatoes", optional: true },
      { slug: "tomato-pasta-sauce", optional: true },
      { slug: "cheese", optional: true },
      { slug: "onions", optional: true },
    ],
    componentSlugs: ["cooked-pasta"],
  },

  // Toast / sandwich
  {
    title: "Cheese Toastie",
    description: "Crispy outside, molten middle.",
    steps: [
      "Butter the outside of two bread slices.",
      "Put cheese between them.",
      "Fry in a pan until both sides are golden and cheese melts.",
    ],
    timeMinutes: 8,
    difficulty: "easy",
    equipment: ["pan", "hob"],
    estimatedCost: "cheap",
    tags: ["toast", "cheese", "one-pan"],
    graphPath: ["cheese-toastie"],
    ingredients: [
      { slug: "bread" },
      { slug: "cheese" },
      { slug: "butter" },
      { slug: "ham", optional: true },
    ],
    componentSlugs: ["cheese-toastie"],
  },
  {
    title: "Cheese on Toast",
    description: "Under the grill. Done.",
    steps: [
      "Toast one side of the bread.",
      "Flip, cover with cheese.",
      "Grill until bubbling.",
    ],
    timeMinutes: 6,
    difficulty: "easy",
    equipment: ["grill", "toaster"],
    estimatedCost: "very_cheap",
    tags: ["toast", "cheese", "barely-any"],
    graphPath: ["cheese-on-toast"],
    ingredients: [
      { slug: "bread" },
      { slug: "cheese" },
      { slug: "worcestershire-sauce", optional: true },
    ],
    componentSlugs: ["cheese-toast"],
  },
  {
    title: "Tuna Mayo Sandwich",
    description: "No hob required.",
    steps: [
      "Mix tuna with mayonnaise.",
      "Spread on bread.",
      "Add cheese or spring onion if you have them.",
    ],
    timeMinutes: 5,
    difficulty: "easy",
    equipment: ["bowl"],
    estimatedCost: "cheap",
    tags: ["sandwich", "tuna", "no-cook"],
    graphPath: ["tuna-mayo-mix"],
    ingredients: [
      { slug: "bread" },
      { slug: "tuna" },
      { slug: "mayonnaise" },
      { slug: "cheese", optional: true },
      { slug: "spring-onions", optional: true },
    ],
    componentSlugs: ["tuna-mayo"],
  },
  {
    title: "Garlic Bread",
    description: "Side dish or main if you're honest.",
    steps: [
      "Mix butter with crushed garlic.",
      "Spread on bread.",
      "Grill until golden.",
    ],
    timeMinutes: 6,
    difficulty: "easy",
    equipment: ["grill"],
    estimatedCost: "very_cheap",
    tags: ["bread", "garlic", "side"],
    graphPath: ["garlic-bread-quick"],
    ingredients: [
      { slug: "bread" },
      { slug: "butter" },
      { slug: "garlic" },
      { slug: "cheese", optional: true },
    ],
    componentSlugs: ["garlic-bread"],
  },

  // Chip meals
  {
    title: "Cheesy Loaded Beans & Chips",
    description: "Oven chips, hot beans, cheese avalanche.",
    steps: [
      "Cook the frozen chips in the oven or air fryer.",
      "Heat the beans.",
      "Pile beans over chips and cover with cheese.",
      "Melt cheese under the grill if needed.",
    ],
    timeMinutes: 22,
    difficulty: "easy",
    equipment: ["oven", "tray", "microwave"],
    estimatedCost: "cheap",
    tags: ["chips", "beans", "cheese"],
    graphPath: ["oven-chips", "heat-beans", "loaded-chips-beans"],
    ingredients: [
      { slug: "frozen-chips" },
      { slug: "baked-beans" },
      { slug: "cheese" },
    ],
    componentSlugs: ["cooked-chips", "hot-beans", "loaded-beans-chips"],
  },
  {
    title: "Egg and Chips",
    description: "Cafe food, student budget.",
    steps: [
      "Cook frozen chips.",
      "Fry eggs in butter or oil.",
      "Serve together with ketchup if you have it.",
    ],
    timeMinutes: 22,
    difficulty: "easy",
    equipment: ["oven", "pan", "hob"],
    estimatedCost: "cheap",
    tags: ["chips", "egg"],
    graphPath: ["oven-chips", "fry-egg-butter"],
    ingredients: [
      { slug: "frozen-chips" },
      { slug: "eggs" },
      { slug: "butter", optional: true },
      { slug: "oil", optional: true },
      { slug: "ketchup", optional: true },
    ],
    componentSlugs: ["cooked-chips", "fried-egg"],
  },
  {
    title: "Cheesy Chips",
    description: "When chips alone aren't enough.",
    steps: [
      "Cook frozen chips.",
      "Cover with grated or sliced cheese.",
      "Return to oven or microwave until melted.",
    ],
    timeMinutes: 22,
    difficulty: "easy",
    equipment: ["oven", "tray"],
    estimatedCost: "cheap",
    tags: ["chips", "cheese", "barely-any"],
    graphPath: ["oven-chips"],
    ingredients: [
      { slug: "frozen-chips" },
      { slug: "cheese" },
    ],
    componentSlugs: ["cooked-chips"],
  },

  // Noodle meals
  {
    title: "Upgraded Instant Noodles",
    description: "Same packet, less sad.",
    steps: [
      "Cook the instant noodles as usual.",
      "Fry or microwave an egg.",
      "Add frozen veg if you have them.",
      "Finish with soy sauce or cheese.",
    ],
    timeMinutes: 8,
    difficulty: "easy",
    equipment: ["kettle", "bowl", "pan"],
    estimatedCost: "very_cheap",
    tags: ["noodles", "egg", "microwave", "convenience"],
    graphPath: ["cook-instant-noodles", "fry-egg-oil", "noodle-egg-bowl"],
    ingredients: [
      { slug: "instant-noodles" },
      { slug: "eggs" },
      { slug: "oil", optional: true },
      { slug: "butter", optional: true },
      { slug: "frozen-mixed-vegetables", optional: true },
      { slug: "soy-sauce", optional: true },
      { slug: "cheese", optional: true },
      { slug: "spring-onions", optional: true },
    ],
    componentSlugs: ["cooked-noodles", "fried-egg", "noodle-egg-bowl"],
  },
  {
    title: "Cheesy Noodle Bowl",
    description: "Instant noodles plus cheese. Controversial, effective.",
    steps: [
      "Cook noodles with less water than usual.",
      "Stir through cheese until glossy.",
      "Add hot sauce if you dare.",
    ],
    timeMinutes: 5,
    difficulty: "easy",
    equipment: ["kettle", "bowl"],
    estimatedCost: "very_cheap",
    tags: ["noodles", "cheese", "microwave", "barely-any"],
    graphPath: ["cook-instant-noodles"],
    ingredients: [
      { slug: "instant-noodles" },
      { slug: "cheese" },
      { slug: "hot-sauce", optional: true },
    ],
    componentSlugs: ["cooked-noodles"],
  },
  {
    title: "Microwave Veg Noodles",
    description: "Noodles and frozen veg, almost no washing up.",
    steps: [
      "Cook instant noodles in a bowl.",
      "Microwave frozen veg separately or tip them in near the end.",
      "Mix and season with soy sauce.",
    ],
    timeMinutes: 7,
    difficulty: "easy",
    equipment: ["kettle", "microwave", "bowl"],
    estimatedCost: "very_cheap",
    tags: ["noodles", "microwave", "vegetarian"],
    graphPath: ["cook-instant-noodles", "microwave-frozen-veg"],
    ingredients: [
      { slug: "instant-noodles" },
      { slug: "frozen-mixed-vegetables" },
      { slug: "soy-sauce", optional: true },
      { slug: "eggs", optional: true },
    ],
    componentSlugs: ["cooked-noodles", "cooked-frozen-veg"],
  },

  // Bean / mushroom / microwave / veggie
  {
    title: "Jacket Potato with Beans and Cheese",
    description: "Microwave potato, proper toppings.",
    steps: [
      "Prick the potato and microwave until soft.",
      "Heat beans.",
      "Split potato, add butter, beans, and cheese.",
    ],
    timeMinutes: 12,
    difficulty: "easy",
    equipment: ["microwave", "bowl"],
    estimatedCost: "cheap",
    tags: ["potato", "beans", "cheese", "microwave", "vegetarian"],
    graphPath: ["microwave-potato", "heat-beans"],
    ingredients: [
      { slug: "potatoes" },
      { slug: "baked-beans" },
      { slug: "cheese" },
      { slug: "butter", optional: true },
    ],
    componentSlugs: ["baked-potato", "hot-beans"],
  },
  {
    title: "Garlic Butter Mushrooms on Toast",
    description: "Pub-side-dish energy, dinner portion.",
    steps: [
      "Fry mushrooms in butter with garlic.",
      "Toast the bread.",
      "Pile mushrooms on toast and add cheese if you want.",
    ],
    timeMinutes: 10,
    difficulty: "easy",
    equipment: ["pan", "hob", "toaster"],
    estimatedCost: "cheap",
    tags: ["mushroom", "toast", "vegetarian"],
    graphPath: ["fry-mushrooms-butter", "toast-bread"],
    ingredients: [
      { slug: "mushrooms" },
      { slug: "butter" },
      { slug: "garlic" },
      { slug: "bread" },
      { slug: "cheese", optional: true },
    ],
    componentSlugs: ["fried-mushrooms", "toast"],
  },
  {
    title: "Microwave Rice and Peas",
    description: "Almost no effort. Still a meal.",
    steps: [
      "Heat microwave rice.",
      "Microwave peas.",
      "Mix with butter, soy, or cheese if available.",
    ],
    timeMinutes: 5,
    difficulty: "easy",
    equipment: ["microwave", "bowl"],
    estimatedCost: "cheap",
    tags: ["rice", "microwave", "vegetarian", "barely-any"],
    graphPath: ["cook-microwave-rice", "microwave-peas"],
    ingredients: [
      { slug: "microwave-rice" },
      { slug: "frozen-peas" },
      { slug: "butter", optional: true },
      { slug: "soy-sauce", optional: true },
      { slug: "cheese", optional: true },
    ],
    componentSlugs: ["cooked-rice", "cooked-peas"],
  },
  {
    title: "Egg-Fried Microwave Rice with Veg",
    description: "Microwave student special.",
    steps: [
      "Heat microwave rice and frozen veg.",
      "Scramble eggs in a pan or microwave.",
      "Mix everything with soy sauce and cheese if you have it.",
    ],
    timeMinutes: 10,
    difficulty: "easy",
    equipment: ["microwave", "pan", "bowl"],
    estimatedCost: "cheap",
    tags: ["rice", "egg", "microwave", "vegetarian"],
    graphPath: ["cook-microwave-rice", "microwave-frozen-veg", "egg-rice"],
    ingredients: [
      { slug: "microwave-rice" },
      { slug: "eggs" },
      { slug: "frozen-mixed-vegetables" },
      { slug: "soy-sauce", optional: true },
      { slug: "cheese", optional: true },
      { slug: "butter", optional: true },
      { slug: "oil", optional: true },
    ],
    componentSlugs: ["cooked-rice", "cooked-frozen-veg", "egg-rice"],
  },
  {
    title: "Sausage, Beans and Chips",
    description: "Full lazy dinner plate.",
    steps: [
      "Cook chips in the oven.",
      "Fry or grill sausages.",
      "Heat beans.",
      "Plate everything. Add cheese if chaotic.",
    ],
    timeMinutes: 25,
    difficulty: "easy",
    equipment: ["oven", "pan", "hob"],
    estimatedCost: "cheap",
    tags: ["chips", "beans", "sausages"],
    graphPath: ["oven-chips", "heat-beans"],
    ingredients: [
      { slug: "frozen-chips" },
      { slug: "sausages" },
      { slug: "baked-beans" },
      { slug: "cheese", optional: true },
    ],
    componentSlugs: ["cooked-chips", "hot-beans"],
  },
  {
    title: "Ham and Cheese Toastie",
    description: "Toastie with actual protein.",
    steps: [
      "Butter bread outsides.",
      "Fill with ham and cheese.",
      "Fry until crisp and melted.",
    ],
    timeMinutes: 8,
    difficulty: "easy",
    equipment: ["pan", "hob"],
    estimatedCost: "cheap",
    tags: ["toast", "cheese", "ham"],
    graphPath: ["cheese-toastie"],
    ingredients: [
      { slug: "bread" },
      { slug: "ham" },
      { slug: "cheese" },
      { slug: "butter" },
    ],
    componentSlugs: ["cheese-toastie"],
  },
  {
    title: "Pea and Cheese Omelette",
    description: "Frozen peas make the omelette feel intentional.",
    steps: [
      "Microwave a handful of peas.",
      "Make an omelette in butter.",
      "Add peas and cheese before folding.",
    ],
    timeMinutes: 10,
    difficulty: "easy",
    equipment: ["pan", "hob", "microwave"],
    estimatedCost: "cheap",
    tags: ["egg", "cheese", "peas", "vegetarian"],
    graphPath: ["microwave-peas", "omelette-base"],
    ingredients: [
      { slug: "eggs" },
      { slug: "frozen-peas" },
      { slug: "cheese" },
      { slug: "butter" },
    ],
    componentSlugs: ["cooked-peas", "omelette"],
  },
  {
    title: "Bacon Egg Rice Bowl",
    description: "Breakfast for dinner energy.",
    steps: [
      "Fry bacon, then eggs in the same pan.",
      "Heat rice.",
      "Serve rice topped with bacon, egg, and optional cheese.",
    ],
    timeMinutes: 12,
    difficulty: "easy",
    equipment: ["pan", "hob", "microwave"],
    estimatedCost: "moderate",
    tags: ["rice", "egg", "bacon"],
    graphPath: ["cook-microwave-rice", "fry-egg-butter"],
    ingredients: [
      { slug: "microwave-rice" },
      { slug: "bacon" },
      { slug: "eggs" },
      { slug: "butter", optional: true },
      { slug: "cheese", optional: true },
      { slug: "soy-sauce", optional: true },
    ],
    componentSlugs: ["cooked-rice", "fried-egg"],
  },
  {
    title: "Tomato Cheese Toast",
    description: "Cheese on toast with tomato slices.",
    steps: [
      "Toast bread.",
      "Top with cheese and sliced tomato.",
      "Grill until cheese melts.",
    ],
    timeMinutes: 7,
    difficulty: "easy",
    equipment: ["grill", "toaster"],
    estimatedCost: "cheap",
    tags: ["toast", "cheese", "tomato", "vegetarian"],
    graphPath: ["cheese-on-toast"],
    ingredients: [
      { slug: "bread" },
      { slug: "cheese" },
      { slug: "tomatoes" },
    ],
    componentSlugs: ["cheese-toast"],
  },
  {
    title: "Spinach Egg Scramble",
    description: "Use the spinach before it dies.",
    steps: [
      "Wilt spinach in butter.",
      "Add beaten eggs and scramble.",
      "Finish with cheese.",
    ],
    timeMinutes: 8,
    difficulty: "easy",
    equipment: ["pan", "hob"],
    estimatedCost: "cheap",
    tags: ["egg", "spinach", "use-soon", "vegetarian"],
    graphPath: ["scramble-egg-butter"],
    ingredients: [
      { slug: "eggs" },
      { slug: "spinach" },
      { slug: "butter" },
      { slug: "cheese", optional: true },
    ],
    componentSlugs: ["scrambled-egg"],
  },
  {
    title: "Chickpea Flatbread Wrap",
    description: "Mash chickpeas into a wrap filling.",
    steps: [
      "Mash chickpeas with oil, salt, and paprika or garlic powder.",
      "Warm a wrap.",
      "Fill and add cheese if available.",
    ],
    timeMinutes: 8,
    difficulty: "easy",
    equipment: ["bowl"],
    estimatedCost: "very_cheap",
    tags: ["wraps", "chickpeas", "vegetarian", "no-cook"],
    graphPath: [],
    ingredients: [
      { slug: "wraps" },
      { slug: "chickpeas" },
      { slug: "oil" },
      { slug: "paprika", optional: true },
      { slug: "garlic-powder", optional: true },
      { slug: "cheese", optional: true },
    ],
    componentSlugs: [],
  },
  {
    title: "Frozen Pizza Upgrade",
    description: "Add fridge leftovers so it feels homemade.",
    steps: [
      "Put frozen pizza on a tray.",
      "Add extra cheese, ham, or mushrooms.",
      "Bake as packet says.",
    ],
    timeMinutes: 18,
    difficulty: "easy",
    equipment: ["oven", "tray"],
    estimatedCost: "moderate",
    tags: ["convenience", "cheese"],
    graphPath: [],
    ingredients: [
      { slug: "frozen-pizza" },
      { slug: "cheese", optional: true },
      { slug: "ham", optional: true },
      { slug: "mushrooms", optional: true },
    ],
    componentSlugs: [],
  },
];
