import type { Difficulty } from "@/lib/types";

export interface TransformationSeed {
  slug: string;
  name: string;
  method: string;
  timeMinutes: number;
  difficulty: Difficulty;
  equipment: string[];
  tags: string[];
  inputs: Array<{
    ingredientSlug?: string;
    componentSlug?: string;
    optional?: boolean;
    role?: string;
  }>;
  outputSlug: string;
  outputName: string;
  outputTags?: string[];
}

export const TRANSFORMATIONS: TransformationSeed[] = [
  // Eggs
  {
    slug: "scramble-egg-butter",
    name: "Scramble eggs in butter",
    method: "pan-fry",
    timeMinutes: 5,
    difficulty: "easy",
    equipment: ["pan", "hob"],
    tags: ["egg", "breakfast"],
    inputs: [
      { ingredientSlug: "eggs" },
      { ingredientSlug: "butter", role: "fat" },
      { ingredientSlug: "milk", optional: true },
      { ingredientSlug: "salt", optional: true },
    ],
    outputSlug: "scrambled-egg",
    outputName: "Scrambled egg",
    outputTags: ["egg", "protein"],
  },
  {
    slug: "fry-egg-oil",
    name: "Fry egg in oil",
    method: "pan-fry",
    timeMinutes: 4,
    difficulty: "easy",
    equipment: ["pan", "hob"],
    tags: ["egg"],
    inputs: [
      { ingredientSlug: "eggs" },
      { ingredientSlug: "oil", role: "fat" },
    ],
    outputSlug: "fried-egg",
    outputName: "Fried egg",
    outputTags: ["egg", "protein"],
  },
  {
    slug: "fry-egg-butter",
    name: "Fry egg in butter",
    method: "pan-fry",
    timeMinutes: 4,
    difficulty: "easy",
    equipment: ["pan", "hob"],
    tags: ["egg"],
    inputs: [
      { ingredientSlug: "eggs" },
      { ingredientSlug: "butter", role: "fat" },
    ],
    outputSlug: "fried-egg",
    outputName: "Fried egg",
    outputTags: ["egg", "protein"],
  },
  {
    slug: "microwave-egg",
    name: "Microwave scrambled egg",
    method: "microwave",
    timeMinutes: 3,
    difficulty: "easy",
    equipment: ["microwave", "bowl"],
    tags: ["egg", "microwave"],
    inputs: [
      { ingredientSlug: "eggs" },
      { ingredientSlug: "milk", optional: true },
      { ingredientSlug: "butter", optional: true },
    ],
    outputSlug: "microwave-scrambled-egg",
    outputName: "Microwave scrambled egg",
    outputTags: ["egg", "microwave"],
  },
  {
    slug: "omelette-base",
    name: "Make plain omelette",
    method: "pan-fry",
    timeMinutes: 6,
    difficulty: "easy",
    equipment: ["pan", "hob"],
    tags: ["egg"],
    inputs: [
      { ingredientSlug: "eggs" },
      { ingredientSlug: "butter", role: "fat" },
      { ingredientSlug: "milk", optional: true },
    ],
    outputSlug: "omelette",
    outputName: "Omelette",
    outputTags: ["egg", "protein"],
  },

  // Aromatics & veg
  {
    slug: "fry-onion-butter",
    name: "Fry onion in butter",
    method: "pan-fry",
    timeMinutes: 6,
    difficulty: "easy",
    equipment: ["pan", "hob"],
    tags: ["aromatic"],
    inputs: [
      { ingredientSlug: "onions" },
      { ingredientSlug: "butter", role: "fat" },
    ],
    outputSlug: "fried-onion",
    outputName: "Fried onion",
    outputTags: ["aromatic", "veg"],
  },
  {
    slug: "fry-onion-oil",
    name: "Fry onion in oil",
    method: "pan-fry",
    timeMinutes: 6,
    difficulty: "easy",
    equipment: ["pan", "hob"],
    tags: ["aromatic"],
    inputs: [
      { ingredientSlug: "onions" },
      { ingredientSlug: "oil", role: "fat" },
    ],
    outputSlug: "fried-onion",
    outputName: "Fried onion",
    outputTags: ["aromatic", "veg"],
  },
  {
    slug: "fry-mushrooms-butter",
    name: "Fry mushrooms in butter",
    method: "pan-fry",
    timeMinutes: 7,
    difficulty: "easy",
    equipment: ["pan", "hob"],
    tags: ["veg"],
    inputs: [
      { ingredientSlug: "mushrooms" },
      { ingredientSlug: "butter", role: "fat" },
      { ingredientSlug: "garlic", optional: true },
    ],
    outputSlug: "fried-mushrooms",
    outputName: "Fried mushrooms",
    outputTags: ["veg"],
  },
  {
    slug: "fry-mushroom-onion",
    name: "Fry mushrooms and onion",
    method: "pan-fry",
    timeMinutes: 8,
    difficulty: "easy",
    equipment: ["pan", "hob"],
    tags: ["veg", "aromatic"],
    inputs: [
      { ingredientSlug: "mushrooms" },
      { ingredientSlug: "onions" },
      { ingredientSlug: "butter", role: "fat" },
      { ingredientSlug: "garlic", optional: true },
    ],
    outputSlug: "fried-mushroom-onion",
    outputName: "Fried mushroom & onion",
    outputTags: ["veg", "aromatic"],
  },
  {
    slug: "soften-garlic-oil",
    name: "Soften garlic in oil",
    method: "pan-fry",
    timeMinutes: 2,
    difficulty: "easy",
    equipment: ["pan", "hob"],
    tags: ["aromatic"],
    inputs: [
      { ingredientSlug: "garlic" },
      { ingredientSlug: "oil", role: "fat" },
    ],
    outputSlug: "softened-garlic",
    outputName: "Softened garlic",
    outputTags: ["aromatic"],
  },
  {
    slug: "microwave-frozen-veg",
    name: "Microwave frozen vegetables",
    method: "microwave",
    timeMinutes: 4,
    difficulty: "easy",
    equipment: ["microwave", "bowl"],
    tags: ["veg", "microwave"],
    inputs: [{ ingredientSlug: "frozen-mixed-vegetables" }],
    outputSlug: "cooked-frozen-veg",
    outputName: "Cooked frozen vegetables",
    outputTags: ["veg", "microwave"],
  },
  {
    slug: "microwave-peas",
    name: "Microwave frozen peas",
    method: "microwave",
    timeMinutes: 3,
    difficulty: "easy",
    equipment: ["microwave", "bowl"],
    tags: ["veg", "microwave"],
    inputs: [{ ingredientSlug: "frozen-peas" }],
    outputSlug: "cooked-peas",
    outputName: "Cooked peas",
    outputTags: ["veg", "microwave"],
  },

  // Carbs
  {
    slug: "toast-bread",
    name: "Toast bread",
    method: "toast",
    timeMinutes: 3,
    difficulty: "easy",
    equipment: ["toaster"],
    tags: ["toast"],
    inputs: [{ ingredientSlug: "bread" }],
    outputSlug: "toast",
    outputName: "Toast",
    outputTags: ["carb", "toast"],
  },
  {
    slug: "butter-toast",
    name: "Butter toast",
    method: "assemble",
    timeMinutes: 1,
    difficulty: "easy",
    equipment: [],
    tags: ["toast"],
    inputs: [
      { componentSlug: "toast" },
      { ingredientSlug: "butter" },
    ],
    outputSlug: "buttered-toast",
    outputName: "Buttered toast",
    outputTags: ["toast"],
  },
  {
    slug: "cheese-on-toast",
    name: "Cheese on toast",
    method: "grill",
    timeMinutes: 5,
    difficulty: "easy",
    equipment: ["grill", "toaster"],
    tags: ["toast", "cheese"],
    inputs: [
      { ingredientSlug: "bread" },
      { ingredientSlug: "cheese" },
      { ingredientSlug: "butter", optional: true },
    ],
    outputSlug: "cheese-toast",
    outputName: "Cheese toast",
    outputTags: ["toast", "cheese"],
  },
  {
    slug: "cheese-toastie",
    name: "Cheese toastie",
    method: "pan-fry",
    timeMinutes: 8,
    difficulty: "easy",
    equipment: ["pan", "hob"],
    tags: ["toast", "cheese"],
    inputs: [
      { ingredientSlug: "bread" },
      { ingredientSlug: "cheese" },
      { ingredientSlug: "butter", role: "fat" },
    ],
    outputSlug: "cheese-toastie",
    outputName: "Cheese toastie",
    outputTags: ["toast", "cheese"],
  },
  {
    slug: "cook-microwave-rice",
    name: "Heat microwave rice",
    method: "microwave",
    timeMinutes: 2,
    difficulty: "easy",
    equipment: ["microwave"],
    tags: ["rice", "microwave"],
    inputs: [{ ingredientSlug: "microwave-rice" }],
    outputSlug: "cooked-rice",
    outputName: "Cooked rice",
    outputTags: ["rice", "carb"],
  },
  {
    slug: "boil-rice",
    name: "Boil rice",
    method: "boil",
    timeMinutes: 12,
    difficulty: "easy",
    equipment: ["pan", "hob"],
    tags: ["rice"],
    inputs: [{ ingredientSlug: "rice" }],
    outputSlug: "cooked-rice",
    outputName: "Cooked rice",
    outputTags: ["rice", "carb"],
  },
  {
    slug: "fried-rice-base",
    name: "Make fried rice base",
    method: "pan-fry",
    timeMinutes: 5,
    difficulty: "easy",
    equipment: ["pan", "hob"],
    tags: ["rice"],
    inputs: [
      { componentSlug: "cooked-rice" },
      { ingredientSlug: "oil", role: "fat" },
      { ingredientSlug: "soy-sauce", optional: true },
    ],
    outputSlug: "fried-rice-base",
    outputName: "Fried rice base",
    outputTags: ["rice"],
  },
  {
    slug: "egg-rice",
    name: "Combine egg and rice",
    method: "pan-fry",
    timeMinutes: 4,
    difficulty: "easy",
    equipment: ["pan", "hob"],
    tags: ["rice", "egg"],
    inputs: [
      { componentSlug: "cooked-rice" },
      { ingredientSlug: "eggs" },
      { ingredientSlug: "oil", optional: true, role: "fat" },
      { ingredientSlug: "butter", optional: true, role: "fat" },
    ],
    outputSlug: "egg-rice",
    outputName: "Egg rice",
    outputTags: ["rice", "egg"],
  },
  {
    slug: "mushroom-egg-fried-rice",
    name: "Mushroom egg fried rice assembly",
    method: "pan-fry",
    timeMinutes: 6,
    difficulty: "easy",
    equipment: ["pan", "hob"],
    tags: ["rice", "egg", "mushroom"],
    inputs: [
      { componentSlug: "fried-mushroom-onion" },
      { componentSlug: "cooked-rice" },
      { ingredientSlug: "eggs" },
      { ingredientSlug: "soy-sauce", optional: true },
      { ingredientSlug: "cheese", optional: true },
    ],
    outputSlug: "mushroom-egg-fried-rice",
    outputName: "Mushroom egg fried rice",
    outputTags: ["rice", "egg", "mushroom", "meal"],
  },
  {
    slug: "boil-pasta",
    name: "Boil pasta",
    method: "boil",
    timeMinutes: 10,
    difficulty: "easy",
    equipment: ["pan", "hob"],
    tags: ["pasta"],
    inputs: [{ ingredientSlug: "pasta" }],
    outputSlug: "cooked-pasta",
    outputName: "Cooked pasta",
    outputTags: ["pasta", "carb"],
  },
  {
    slug: "cook-instant-noodles",
    name: "Cook instant noodles",
    method: "boil",
    timeMinutes: 4,
    difficulty: "easy",
    equipment: ["kettle", "bowl"],
    tags: ["noodles", "convenience"],
    inputs: [{ ingredientSlug: "instant-noodles" }],
    outputSlug: "cooked-noodles",
    outputName: "Cooked noodles",
    outputTags: ["noodles", "carb"],
  },
  {
    slug: "boil-noodles",
    name: "Boil noodles",
    method: "boil",
    timeMinutes: 6,
    difficulty: "easy",
    equipment: ["pan", "hob"],
    tags: ["noodles"],
    inputs: [{ ingredientSlug: "noodles" }],
    outputSlug: "cooked-noodles",
    outputName: "Cooked noodles",
    outputTags: ["noodles", "carb"],
  },
  {
    slug: "oven-chips",
    name: "Cook frozen chips",
    method: "oven",
    timeMinutes: 20,
    difficulty: "easy",
    equipment: ["oven", "tray"],
    tags: ["chips"],
    inputs: [{ ingredientSlug: "frozen-chips" }],
    outputSlug: "cooked-chips",
    outputName: "Cooked chips",
    outputTags: ["chips", "carb"],
  },
  {
    slug: "airfry-chips",
    name: "Air-fry frozen chips",
    method: "air-fry",
    timeMinutes: 15,
    difficulty: "easy",
    equipment: ["air-fryer"],
    tags: ["chips"],
    inputs: [{ ingredientSlug: "frozen-chips" }],
    outputSlug: "cooked-chips",
    outputName: "Cooked chips",
    outputTags: ["chips", "carb"],
  },
  {
    slug: "microwave-potato",
    name: "Microwave potato",
    method: "microwave",
    timeMinutes: 8,
    difficulty: "easy",
    equipment: ["microwave"],
    tags: ["potato", "microwave"],
    inputs: [
      { ingredientSlug: "potatoes" },
      { ingredientSlug: "microwave-potatoes", optional: true },
    ],
    outputSlug: "baked-potato",
    outputName: "Baked potato",
    outputTags: ["potato", "carb"],
  },
  {
    slug: "roast-potatoes",
    name: "Roast potatoes in oil",
    method: "oven",
    timeMinutes: 30,
    difficulty: "medium",
    equipment: ["oven", "tray"],
    tags: ["potato"],
    inputs: [
      { ingredientSlug: "potatoes" },
      { ingredientSlug: "oil", role: "fat" },
    ],
    outputSlug: "roasted-potatoes",
    outputName: "Roasted potatoes",
    outputTags: ["potato", "carb"],
  },

  // Sauces & beans
  {
    slug: "heat-beans",
    name: "Heat baked beans",
    method: "microwave",
    timeMinutes: 2,
    difficulty: "easy",
    equipment: ["microwave", "bowl"],
    tags: ["beans"],
    inputs: [{ ingredientSlug: "baked-beans" }],
    outputSlug: "hot-beans",
    outputName: "Hot beans",
    outputTags: ["beans", "protein"],
  },
  {
    slug: "basic-tomato-sauce",
    name: "Basic tomato sauce",
    method: "simmer",
    timeMinutes: 12,
    difficulty: "easy",
    equipment: ["pan", "hob"],
    tags: ["sauce"],
    inputs: [
      { ingredientSlug: "chopped-tomatoes" },
      { ingredientSlug: "onions" },
      { ingredientSlug: "garlic" },
      { ingredientSlug: "oil", role: "fat" },
      { ingredientSlug: "stock-cubes", optional: true },
    ],
    outputSlug: "basic-tomato-sauce",
    outputName: "Basic tomato sauce",
    outputTags: ["sauce"],
  },
  {
    slug: "quick-pasta-sauce",
    name: "Heat pasta sauce",
    method: "microwave",
    timeMinutes: 3,
    difficulty: "easy",
    equipment: ["microwave", "bowl"],
    tags: ["sauce", "convenience"],
    inputs: [
      { ingredientSlug: "tomato-pasta-sauce" },
      { ingredientSlug: "garlic", optional: true },
    ],
    outputSlug: "ready-pasta-sauce",
    outputName: "Ready pasta sauce",
    outputTags: ["sauce"],
  },
  {
    slug: "curry-sauce-quick",
    name: "Heat ready curry with veg",
    method: "microwave",
    timeMinutes: 6,
    difficulty: "easy",
    equipment: ["microwave", "bowl"],
    tags: ["curry", "convenience"],
    inputs: [
      { ingredientSlug: "ready-made-curry" },
      { ingredientSlug: "frozen-mixed-vegetables", optional: true },
    ],
    outputSlug: "quick-curry",
    outputName: "Quick curry",
    outputTags: ["curry", "sauce"],
  },
  {
    slug: "chickpea-curry-base",
    name: "Chickpea curry base",
    method: "simmer",
    timeMinutes: 12,
    difficulty: "easy",
    equipment: ["pan", "hob"],
    tags: ["curry", "veggie"],
    inputs: [
      { ingredientSlug: "chickpeas" },
      { ingredientSlug: "chopped-tomatoes" },
      { ingredientSlug: "onions" },
      { ingredientSlug: "curry-powder" },
      { ingredientSlug: "oil", role: "fat" },
      { ingredientSlug: "garlic", optional: true },
    ],
    outputSlug: "chickpea-curry",
    outputName: "Chickpea curry",
    outputTags: ["curry", "veggie", "protein"],
  },

  // Composite meal components
  {
    slug: "cheesy-egg-toast-assembly",
    name: "Cheesy egg toast",
    method: "assemble",
    timeMinutes: 8,
    difficulty: "easy",
    equipment: ["pan", "hob", "toaster"],
    tags: ["toast", "egg", "cheese"],
    inputs: [
      { componentSlug: "toast" },
      { componentSlug: "fried-egg" },
      { ingredientSlug: "cheese" },
    ],
    outputSlug: "cheesy-egg-toast",
    outputName: "Cheesy egg toast",
    outputTags: ["toast", "egg", "meal"],
  },
  {
    slug: "loaded-chips-beans",
    name: "Loaded chips with beans and cheese",
    method: "assemble",
    timeMinutes: 5,
    difficulty: "easy",
    equipment: ["bowl"],
    tags: ["chips", "beans", "cheese"],
    inputs: [
      { componentSlug: "cooked-chips" },
      { componentSlug: "hot-beans" },
      { ingredientSlug: "cheese" },
    ],
    outputSlug: "loaded-beans-chips",
    outputName: "Cheesy loaded beans & chips",
    outputTags: ["chips", "beans", "meal"],
  },
  {
    slug: "veg-curry-rice",
    name: "Vegetable curry rice",
    method: "assemble",
    timeMinutes: 4,
    difficulty: "easy",
    equipment: ["bowl"],
    tags: ["curry", "rice"],
    inputs: [
      { componentSlug: "quick-curry" },
      { componentSlug: "cooked-rice" },
      { componentSlug: "cooked-frozen-veg", optional: true },
    ],
    outputSlug: "veg-curry-rice",
    outputName: "Quick vegetable curry rice",
    outputTags: ["curry", "rice", "meal"],
  },
  {
    slug: "tuna-mayo-mix",
    name: "Mix tuna mayo",
    method: "assemble",
    timeMinutes: 3,
    difficulty: "easy",
    equipment: ["bowl"],
    tags: ["tuna"],
    inputs: [
      { ingredientSlug: "tuna" },
      { ingredientSlug: "mayonnaise" },
      { ingredientSlug: "spring-onions", optional: true },
    ],
    outputSlug: "tuna-mayo",
    outputName: "Tuna mayo",
    outputTags: ["protein", "cold"],
  },
  {
    slug: "garlic-bread-quick",
    name: "Quick garlic bread",
    method: "grill",
    timeMinutes: 5,
    difficulty: "easy",
    equipment: ["grill"],
    tags: ["bread", "garlic"],
    inputs: [
      { ingredientSlug: "bread" },
      { ingredientSlug: "butter" },
      { ingredientSlug: "garlic" },
    ],
    outputSlug: "garlic-bread",
    outputName: "Garlic bread",
    outputTags: ["bread"],
  },
  {
    slug: "cheesy-beans-on-toast",
    name: "Cheesy beans on toast",
    method: "assemble",
    timeMinutes: 5,
    difficulty: "easy",
    equipment: ["toaster", "microwave"],
    tags: ["beans", "toast", "cheese"],
    inputs: [
      { componentSlug: "toast" },
      { componentSlug: "hot-beans" },
      { ingredientSlug: "cheese" },
    ],
    outputSlug: "cheesy-beans-toast",
    outputName: "Cheesy beans on toast",
    outputTags: ["beans", "toast", "meal"],
  },
  {
    slug: "noodle-egg-bowl",
    name: "Noodle egg bowl",
    method: "assemble",
    timeMinutes: 6,
    difficulty: "easy",
    equipment: ["kettle", "bowl", "pan"],
    tags: ["noodles", "egg"],
    inputs: [
      { componentSlug: "cooked-noodles" },
      { componentSlug: "fried-egg" },
      { ingredientSlug: "soy-sauce", optional: true },
      { ingredientSlug: "spring-onions", optional: true },
      { ingredientSlug: "frozen-mixed-vegetables", optional: true },
    ],
    outputSlug: "noodle-egg-bowl",
    outputName: "Noodle egg bowl",
    outputTags: ["noodles", "egg", "meal"],
  },
  {
    slug: "pasta-tomato-cheese",
    name: "Pasta with tomato and cheese",
    method: "assemble",
    timeMinutes: 5,
    difficulty: "easy",
    equipment: ["pan", "bowl"],
    tags: ["pasta", "cheese"],
    inputs: [
      { componentSlug: "cooked-pasta" },
      { componentSlug: "ready-pasta-sauce", optional: true },
      { componentSlug: "basic-tomato-sauce", optional: true },
      { ingredientSlug: "cheese" },
    ],
    outputSlug: "cheesy-tomato-pasta",
    outputName: "Cheesy tomato pasta",
    outputTags: ["pasta", "cheese", "meal"],
  },
  {
    slug: "fry-mince-onion",
    name: "Fry mince with onion",
    method: "pan-fry",
    timeMinutes: 12,
    difficulty: "easy",
    equipment: ["pan", "hob"],
    tags: ["mince", "protein", "meal-base"],
    inputs: [
      { ingredientSlug: "mince" },
      { ingredientSlug: "onions" },
      { ingredientSlug: "oil", optional: true, role: "fat" },
      { ingredientSlug: "garlic", optional: true },
      { ingredientSlug: "worcestershire-sauce", optional: true },
    ],
    outputSlug: "cooked-mince",
    outputName: "Cooked mince",
    outputTags: ["protein", "meat", "meal-base"],
  },
  {
    slug: "mince-tomato-pasta",
    name: "Mince tomato pasta",
    method: "assemble",
    timeMinutes: 8,
    difficulty: "easy",
    equipment: ["pan", "hob"],
    tags: ["pasta", "mince", "meal"],
    inputs: [
      { componentSlug: "cooked-pasta" },
      { componentSlug: "cooked-mince" },
      { ingredientSlug: "chopped-tomatoes" },
      { ingredientSlug: "cheese", optional: true },
    ],
    outputSlug: "mince-pasta",
    outputName: "Mince pasta",
    outputTags: ["pasta", "mince", "meal"],
  },
  {
    slug: "soft-celery-onion",
    name: "Soften celery and onion",
    method: "pan-fry",
    timeMinutes: 6,
    difficulty: "easy",
    equipment: ["pan", "hob"],
    tags: ["veg", "aromatic"],
    inputs: [
      { ingredientSlug: "celery" },
      { ingredientSlug: "onions" },
      { ingredientSlug: "oil", optional: true, role: "fat" },
      { ingredientSlug: "butter", optional: true, role: "fat" },
    ],
    outputSlug: "soft-aromatics",
    outputName: "Soft aromatics",
    outputTags: ["veg", "aromatic"],
  },
  {
    slug: "lentil-tomato-pot",
    name: "Simmer lentils with tomatoes",
    method: "simmer",
    timeMinutes: 20,
    difficulty: "easy",
    equipment: ["pan", "hob"],
    tags: ["lentils", "meal"],
    inputs: [
      { ingredientSlug: "lentils" },
      { ingredientSlug: "chopped-tomatoes" },
      { ingredientSlug: "onions", optional: true },
      { ingredientSlug: "stock-cubes", optional: true },
      { ingredientSlug: "curry-powder", optional: true },
    ],
    outputSlug: "lentil-stew",
    outputName: "Lentil stew",
    outputTags: ["lentils", "meal", "veggie"],
  },
];
